# Authelia Configuration
# https://www.authelia.com/configuration/
# Secrets are loaded from environment variables via .env (dotenv in Taskfile)

theme: dark

server:
  address: tcp://0.0.0.0:9091

log:
  level: debug

totp:
  issuer: authelia.com

identity_validation:
  reset_password:
    jwt_secret: insecure_jwt_secret

authentication_backend:
  file:
    path: /tmp/authelia/users_database.yml

access_control:
  default_policy: one_factor

session:
  secret: insecure_session_secret
  cookies:
    - domain: 127.0.0.1
      authelia_url: https://127.0.0.1:9091

storage:
  encryption_key: insecure_encryption_key
  local:
    path: /tmp/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /tmp/authelia/notification.txt
